/**
 * Platform model registry.
 *
 * Imports every entity declaration and exposes a flat keyed lookup
 * (`MODEL_REGISTRY`) plus convenience accessors used by the introspection
 * API and the `platform.describe_entity` / `platform.list_entities`
 * agent tools.
 *
 * NOTE: this file is regenerated by the backfill agent as new entities
 * are registered. Add new models by importing them and adding them to
 * the registry literal.
 */

import type { ModelMeta } from './types'
import { hdTicketModel } from './hd-ticket'
import { crmContactModel } from './crm-contact'
import { crmDealModel } from './crm-deal'

export const MODEL_REGISTRY: Record<string, ModelMeta> = {
  [hdTicketModel.entity]:   hdTicketModel,
  [crmContactModel.entity]: crmContactModel,
  [crmDealModel.entity]:    crmDealModel,
}

export function getModel(entity: string): ModelMeta | null {
  return MODEL_REGISTRY[entity] ?? null
}

export function listEntities(): string[] {
  return Object.keys(MODEL_REGISTRY)
}

export type { ModelMeta }
