/**
 * Platform model registry.
 *
 * Imports every entity declaration and exposes a flat keyed lookup
 * (`MODEL_REGISTRY`) plus convenience accessors used by the introspection
 * API and the `platform.describe_entity` / `platform.list_entities`
 * agent tools.
 *
 * NOTE: this file is regenerated by the backfill agent as new entities
 * are registered. Add new models by importing them and adding them to
 * the registry literal.
 */

import type { ModelMeta } from './types'
import { hdTicketModel } from './hd-ticket'
import { crmContactModel } from './crm-contact'
import { crmDealModel } from './crm-deal'
import { finInvoiceModel } from './fin-invoice'
import { finBillModel } from './fin-bill'
import { salesOrderModel } from './sales-order'
import { procOrderModel } from './proc-order'
import { invProductModel } from './inv-product'
import { hrEmployeeModel } from './hr-employee'
import { payPayslipModel } from './pay-payslip'
import { projProjectModel } from './proj-project'
import { projTaskModel } from './proj-task'
import { emailAccountModel } from './email-account'
import { emailThreadModel } from './email-thread'
import { omniChannelModel } from './omni-channel'
import { omniConversationModel } from './omni-conversation'
import { kmsArticleModel } from './kms-article'

export const MODEL_REGISTRY: Record<string, ModelMeta> = {
  [hdTicketModel.entity]:         hdTicketModel,
  [crmContactModel.entity]:       crmContactModel,
  [crmDealModel.entity]:          crmDealModel,
  [finInvoiceModel.entity]:       finInvoiceModel,
  [finBillModel.entity]:          finBillModel,
  [salesOrderModel.entity]:       salesOrderModel,
  [procOrderModel.entity]:        procOrderModel,
  [invProductModel.entity]:       invProductModel,
  [hrEmployeeModel.entity]:       hrEmployeeModel,
  [payPayslipModel.entity]:       payPayslipModel,
  [projProjectModel.entity]:      projProjectModel,
  [projTaskModel.entity]:         projTaskModel,
  [emailAccountModel.entity]:     emailAccountModel,
  [emailThreadModel.entity]:      emailThreadModel,
  [omniChannelModel.entity]:      omniChannelModel,
  [omniConversationModel.entity]: omniConversationModel,
  [kmsArticleModel.entity]:       kmsArticleModel,
}

export function getModel(entity: string): ModelMeta | null {
  return MODEL_REGISTRY[entity] ?? null
}

export function listEntities(): string[] {
  return Object.keys(MODEL_REGISTRY)
}

export type { ModelMeta }
