/**
 * Platform model metadata — machine-readable descriptions of every entity
 * in KantorCore. Read by IS-AGENT for introspection and (eventually) by the
 * Record Kit to drive ListView / FormView / KanbanView rendering.
 *
 * These declarations DO NOT yet drive UI. They mirror the bespoke modules
 * that exist today. The contract is: if a field is added to the DB, it's
 * added here too. The metadata is the single source of truth for "what
 * this system contains" from an agent's perspective.
 */

// ── Field type system ─────────────────────────────────────────────────────────

export type FieldType =
  | 'text'         // short string
  | 'longtext'     // multi-line plain string
  | 'html'         // rich text (TipTap JSON)
  | 'integer'
  | 'decimal'
  | 'monetary'     // amount + currency (default IDR)
  | 'boolean'
  | 'date'
  | 'datetime'
  | 'enum'         // bounded choices, see `options`
  | 'many2one'     // FK to another entity, see `target`
  | 'one2many'     // reverse FK / lines, see `target` + `inverseField`
  | 'many2many'    // join table relation, see `target`
  | 'file'
  | 'image'
  | 'signature'
  | 'json'         // freeform structured data
  | 'tags'         // free-form string array
  | 'phone'
  | 'email'
  | 'url'
  | 'address'
  | 'ai-field'     // computed/generated by an LLM at write time

export type FieldWidget =
  | 'text' | 'textarea' | 'rich-text'
  | 'monetary' | 'percent' | 'rating' | 'progress'
  | 'priority' | 'badge' | 'color' | 'tag-input'
  | 'select' | 'radio' | 'checkbox'
  | 'date-picker' | 'datetime-picker' | 'date-range'
  | 'avatar-select' | 'reference'
  | 'image-upload' | 'file-upload' | 'signature-pad'
  | 'json-editor'
  | 'address-form'

export interface FieldMeta {
  /** Internal field name; matches the DB column (camelCase). */
  name: string
  /** Human label (Indonesian). */
  label: string
  type: FieldType
  /** Optional widget override; if absent, sensible default for the type. */
  widget?: FieldWidget
  required?: boolean
  readonly?: boolean
  default?: unknown
  /** Inline options for `enum`. */
  options?: { value: string; label: string }[]
  /** Target entity name for relational fields (e.g. 'platform.user'). */
  target?: string
  /** For `one2many`, the FK field on the target side. */
  inverseField?: string
  /** Currency code for `monetary`. Defaults to 'IDR'. */
  currency?: string
  /** Help text shown to humans AND used by the agent as context. */
  help?: string
  /** True if this field appears in global search results. */
  searchable?: boolean
}

// ── View metadata ─────────────────────────────────────────────────────────────

/**
 * Form layout: an array of rows. Each row is either a single field name
 * (full-width) or an array of field names (split equally across columns).
 * Tabs group rows under labels.
 */
export type FormRow = string | string[]
export type FormTab = { id: string; label: string; rows: FormRow[] }

export interface ListViewMeta {
  columns: string[]
  defaultSort?: { field: string; direction: 'asc' | 'desc' }
  /** Field names that drive filter chips in the list header. */
  filters?: string[]
}

export interface FormViewMeta {
  /** Top-level rows shown above tabs. */
  rows?: FormRow[]
  tabs?: FormTab[]
}

export interface KanbanViewMeta {
  groupBy: string
  cardTitle: string
  cardFields?: string[]
}

export interface ViewMeta {
  list?: ListViewMeta
  form?: FormViewMeta
  kanban?: KanbanViewMeta
}

// ── Permissions ───────────────────────────────────────────────────────────────

/**
 * Role tiers from most → least privileged. `agent` = an IS-AGENT acting on
 * behalf of a user. `owner` = the user who created the record. `public` =
 * unauthenticated (portal/widget visitors).
 */
export type Role = 'admin' | 'member' | 'agent' | 'owner' | 'public'

export interface PermissionMeta {
  create?: Role[]
  read?: Role[]
  update?: Role[]
  delete?: Role[]
}

// ── Model ─────────────────────────────────────────────────────────────────────

export interface ModelMeta {
  /** Namespaced identifier: 'hd.ticket', 'crm.deal'. Stable; do not rename. */
  entity: string
  /** Owning module code (e.g. 'IS-HD'). */
  module: string
  /** Singular human label. */
  label: string
  pluralLabel: string
  /** Field used as the human-readable name of a record. */
  displayField: string
  fields: Record<string, FieldMeta>
  views: ViewMeta
  perms: PermissionMeta
  /** Does this entity participate in polymorphic chatter? */
  chatter?: boolean
  /** Does this entity support scheduled activities (separately from chatter)? */
  activities?: boolean
  /** Entity-level description for the agent. */
  help?: string
}
