/**
 * Schema barrel. Every table in every module re-exports from here so
 * drizzle-kit picks them up via a single import path.
 */

export * from './tenants'
export * from './users'
export * from './sessions'
export * from './memberships'
export * from './chat'
export * from './proj'
export * from './agent'
export * from './invites'
export * from './audit'
export * from './password-reset'
export * from './totp-challenges'
export * from './hr'
export * from './rent'
export * from './processes'
export * from './fin'
export * from './pay'
export * from './admin'
export * from './contacts'
export * from './inv'
export * from './proc'
export * from './sales'
export * from './crm'
export * from './doc'
export * from './mig'
export * from './trig'
export * from './promo'
export * from './portal'
export * from './hd'
export * from './kms'
export * from './blocks'
export * from './email'
